### ISSUE TITLE
Bug: Wrong icon path in admin template

### ISSUE THREAD

**Issue by JuKu** [JuKu/JuKuCMS#213]
Fix path from icon in admin template.

**Comment by JuKu** [comment]
CSS Code:
```css
.main-header .sidebar-toggle:before {
  content: "\f0c9";
}
```

HTML Code:
```html
<!-- Sidebar toggle button-->
<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
```

Maybe it is a problem with ionicons:
https://ionicons.com/v1/cheatsheet.html
